#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PorAka.Resource", IsApplication=true)]

namespace PorAka
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int PlanetsArray = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int Bar = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FondoAzul = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int FondoBlando = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_other = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_card = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BntAmarillo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BntVerde = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int container_dropshadow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drawer_shadow_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int drawer_shadow_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fondo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int gradient_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int gradient_bg_hover = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int headertext = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_action_find_replace = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_action_loyalty = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_action_shopping_cart = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_action_thumb = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_action_thumb_up = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_communication_location_on = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_hardware_phone_iphone = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_maps_local_offer = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_maps_local_post_office = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_social_person = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_social_share = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_drawer_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_drawer_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_stat_checka = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_stat_icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int image_bg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int list_selector = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int monoandroidsplash = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int splahs = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int splash_background = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int user = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09003c
			public const int BtnAplicarOferta = 2131296316;
			
			// aapt resource value: 0x7f09002e
			public const int BtnCall = 2131296302;
			
			// aapt resource value: 0x7f09003b
			public const int BtnCount = 2131296315;
			
			// aapt resource value: 0x7f090045
			public const int BtnIniciar = 2131296325;
			
			// aapt resource value: 0x7f09002d
			public const int BtnNavegar = 2131296301;
			
			// aapt resource value: 0x7f090012
			public const int BtnPrecios = 2131296274;
			
			// aapt resource value: 0x7f090051
			public const int BtnRegistar = 2131296337;
			
			// aapt resource value: 0x7f090046
			public const int BtnRegister = 2131296326;
			
			// aapt resource value: 0x7f090005
			public const int ChBoxAGarantia = 2131296261;
			
			// aapt resource value: 0x7f09004f
			public const int ChBoxTerminos = 2131296335;
			
			// aapt resource value: 0x7f090004
			public const int ChboxAEnvio = 2131296260;
			
			// aapt resource value: 0x7f090034
			public const int GView = 2131296308;
			
			// aapt resource value: 0x7f090002
			public const int ImgAProduct = 2131296258;
			
			// aapt resource value: 0x7f09004a
			public const int ImgLogin = 2131296330;
			
			// aapt resource value: 0x7f09001e
			public const int ImgLogo = 2131296286;
			
			// aapt resource value: 0x7f090014
			public const int ImgMenu = 2131296276;
			
			// aapt resource value: 0x7f090018
			public const int ImgPro = 2131296280;
			
			// aapt resource value: 0x7f090039
			public const int ImgProduct = 2131296313;
			
			// aapt resource value: 0x7f09000a
			public const int ImgVPro = 2131296266;
			
			// aapt resource value: 0x7f090036
			public const int ImgView = 2131296310;
			
			// aapt resource value: 0x7f09001f
			public const int LLayout = 2131296287;
			
			// aapt resource value: 0x7f090049
			public const int LVOfertas = 2131296329;
			
			// aapt resource value: 0x7f090053
			public const int ListVOfertas = 2131296339;
			
			// aapt resource value: 0x7f090041
			public const int ListVProduct = 2131296321;
			
			// aapt resource value: 0x7f090035
			public const int LyItem = 2131296309;
			
			// aapt resource value: 0x7f090037
			public const int PBar = 2131296311;
			
			// aapt resource value: 0x7f09000b
			public const int ProBar = 2131296267;
			
			// aapt resource value: 0x7f090000
			public const int TxtAProduct = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int TxtAValorOferta = 2131296264;
			
			// aapt resource value: 0x7f09002a
			public const int TxtAddress = 2131296298;
			
			// aapt resource value: 0x7f09004e
			public const int TxtCComercial = 2131296334;
			
			// aapt resource value: 0x7f090040
			public const int TxtCategory = 2131296320;
			
			// aapt resource value: 0x7f090028
			public const int TxtCelular = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int TxtCentroC = 2131296297;
			
			// aapt resource value: 0x7f090020
			public const int TxtCiudad = 2131296288;
			
			// aapt resource value: 0x7f09001d
			public const int TxtComercial = 2131296285;
			
			// aapt resource value: 0x7f090027
			public const int TxtContact = 2131296295;
			
			// aapt resource value: 0x7f090038
			public const int TxtDetail = 2131296312;
			
			// aapt resource value: 0x7f09002b
			public const int TxtEmail = 2131296299;
			
			// aapt resource value: 0x7f09004b
			public const int TxtEntrar = 2131296331;
			
			// aapt resource value: 0x7f090021
			public const int TxtGarantia = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int TxtIsGarantia = 2131296290;
			
			// aapt resource value: 0x7f090025
			public const int TxtIsSend = 2131296293;
			
			// aapt resource value: 0x7f09000e
			public const int TxtLike = 2131296270;
			
			// aapt resource value: 0x7f090015
			public const int TxtName = 2131296277;
			
			// aapt resource value: 0x7f090043
			public const int TxtNit = 2131296323;
			
			// aapt resource value: 0x7f090050
			public const int TxtNombres = 2131296336;
			
			// aapt resource value: 0x7f09004d
			public const int TxtPCargo = 2131296333;
			
			// aapt resource value: 0x7f090026
			public const int TxtPrecio = 2131296294;
			
			// aapt resource value: 0x7f09000c
			public const int TxtProduct = 2131296268;
			
			// aapt resource value: 0x7f090044
			public const int TxtPwd = 2131296324;
			
			// aapt resource value: 0x7f09004c
			public const int TxtRSocial = 2131296332;
			
			// aapt resource value: 0x7f09003e
			public const int TxtRanking = 2131296318;
			
			// aapt resource value: 0x7f09001a
			public const int TxtSale = 2131296282;
			
			// aapt resource value: 0x7f09000d
			public const int TxtSales = 2131296269;
			
			// aapt resource value: 0x7f090042
			public const int TxtTypeUser = 2131296322;
			
			// aapt resource value: 0x7f09003a
			public const int TxtUser = 2131296314;
			
			// aapt resource value: 0x7f09003f
			public const int TxtnVedidos = 2131296319;
			
			// aapt resource value: 0x7f090011
			public const int WebDetalis = 2131296273;
			
			// aapt resource value: 0x7f090054
			public const int action_websearch = 2131296340;
			
			// aapt resource value: 0x7f09001b
			public const int button1 = 2131296283;
			
			// aapt resource value: 0x7f090031
			public const int content_frame = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int drawer_layout = 2131296304;
			
			// aapt resource value: 0x7f090032
			public const int left_drawer = 2131296306;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int linearLayout2 = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout3 = 2131296262;
			
			// aapt resource value: 0x7f090023
			public const int linearLayout4 = 2131296291;
			
			// aapt resource value: 0x7f090019
			public const int linearLayout5 = 2131296281;
			
			// aapt resource value: 0x7f090016
			public const int linearLayout6 = 2131296278;
			
			// aapt resource value: 0x7f09002c
			public const int linearLayout7 = 2131296300;
			
			// aapt resource value: 0x7f09001c
			public const int linearLayout8 = 2131296284;
			
			// aapt resource value: 0x7f090052
			public const int progressBar1 = 2131296338;
			
			// aapt resource value: 0x7f090033
			public const int relativeLayout1 = 2131296307;
			
			// aapt resource value: 0x7f090009
			public const int scrollView1 = 2131296265;
			
			// aapt resource value: 0x7f090047
			public const int sliding_tabs = 2131296327;
			
			// aapt resource value: 0x7f09003d
			public const int textView1 = 2131296317;
			
			// aapt resource value: 0x7f090007
			public const int textView2 = 2131296263;
			
			// aapt resource value: 0x7f090010
			public const int textView3 = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int textView4 = 2131296271;
			
			// aapt resource value: 0x7f090024
			public const int textView5 = 2131296292;
			
			// aapt resource value: 0x7f090017
			public const int textView6 = 2131296279;
			
			// aapt resource value: 0x7f09002f
			public const int textView7 = 2131296303;
			
			// aapt resource value: 0x7f090013
			public const int thumbnail = 2131296275;
			
			// aapt resource value: 0x7f090048
			public const int viewpager = 2131296328;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AplicarOfertaView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailsProductFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrawerListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InfCMFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InitActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InitFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ItemGrid = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ItemListaPrecios = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ItemListOfertas = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ItemListProduct = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListProductFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LoginCMFragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MyShopFragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int OfertasFragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int pager_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ProcessBarView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int RegisterCMFragment = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int RegisterUserFragment = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SubastaFragment = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int DrawerClose = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int DrawerOpen = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int action_slidingpane = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int action_websearch = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int app_not_available = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int mp3_url = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int pause = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int play = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int sliding_pane_layout_summary = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int stop = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int BaseTheme = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int Mono_Android_Theme_Splash = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int StyleLayout = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int Theme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int TxtAzulColor = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
